# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets


class addEditCoffeeFormUi(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setUi()

    def setUi(self):
        self.setObjectName("self")
        self.resize(400, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(self)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.wdegree = QtWidgets.QLineEdit(self)
        self.wdegree.setObjectName("wdegree")
        self.gridLayout.addWidget(self.wdegree, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 0, 1, 2)
        self.wtype = QtWidgets.QLineEdit(self)
        self.wtype.setObjectName("wtype")
        self.gridLayout.addWidget(self.wtype, 2, 1, 1, 1)
        self.wtaste = QtWidgets.QLineEdit(self)
        self.wtaste.setObjectName("wtaste")
        self.gridLayout.addWidget(self.wtaste, 3, 1, 1, 1)
        self.wtitle = QtWidgets.QLineEdit(self)
        self.wtitle.setObjectName("wtitle")
        self.gridLayout.addWidget(self.wtitle, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.wprice = QtWidgets.QSpinBox(self)
        self.wprice.setMaximum(99999999)
        self.wprice.setObjectName("wprice")
        self.gridLayout.addWidget(self.wprice, 4, 1, 1, 1)
        self.wamount = QtWidgets.QSpinBox(self)
        self.wamount.setMaximum(99999999)
        self.wamount.setObjectName("wamount")
        self.gridLayout.addWidget(self.wamount, 5, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "self"))
        self.label.setText(_translate("self", "Обьем"))
        self.label_2.setText(_translate("self", "Цена"))
        self.label_3.setText(_translate("self", "Описание вкуса"))
        self.label_4.setText(_translate("self", "Молотый/в зернах"))
        self.label_5.setText(_translate("self", "Обжарка"))
        self.label_6.setText(_translate("self", "Название"))
